"""empty message

Revision ID: 06fb7a7c63c3
Revises: 0e80f3f67341
Create Date: 2024-10-09 16:02:02.038443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fb7a7c63c3'
down_revision = '0e80f3f67341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
